import 'package:get/get_navigation/src/root/internacionalization.dart';

class Strings extends Translations{
  @override

  Map<String, Map<String, String>> get keys =>{
    'ar':{
      'sign_in':'تسجيل دخول',
      'sign_up':'انشاء حساب',
      'enter_your_email':'ادخل البريد الاكتروني',
      'enter_your_password':'ادخل كلمة السر',
      'dont_have_an_account':'لا يوجد لديك حساب',
      'member_of_princess_nourah_university':'عضو في جامعة الاميرة نوره',
      'No_I_am_not_a_member':'لا انا لست عضو',
      'Enter_your_Full_Name':'ادخل اسمك الكامل',
      'Enter_your_ID_Number':'ادخل رقمك الجامعي',
      'Enter_your_Phone_Number':'ادخل رقم هاتفك',
      'Enter_your_Age':'ادخل عمرك',
      'register':'تسجيل دخول',
      'Already_have_an_account_?':'هل لديك حساب بالفعل ؟',
      'Setting_Screen':'الاعدادات',
      'Classes_Screen':'الحصص الرياضياة',
      'Home_Screen':'الشاشة الرئيسية',
      'Menu':'القائمة',
      'account':'الحساب',
      'contact_us':'تواصل معنا',
      'logout':'تسجيل خروج',
      'home':'الرئيسية',
      'classes':'الحصص',
      'setting':'الاعدادات',
      'announcements':'الملاحظات',
      'There is no announcment':'لا يوجد ملاحظات',
      'class_title:':'عنوان الحصة : ',
      'coach_name_:':'اسم الكوتش :',
      'Time_for_the_Class_:':'وقت الحصة : ',
      'accept':'قبول',
      'decline':'رفض',
      'My_Classes':'حصصي',
      'language':'اللغة',
      'edit_profile':'تعديل الحساب',
      'about_app':'عن التطبيق',
      'help':'المساعدة',
      'Profile_Screen':'الحساب الشخصي',
      'Get_in_touch_with_a_member_of_our_coaching_staff.':'تواصل مع أحد أعضاء طاقم التدريب لدينا.',
      'Write you_message_here':'اكتب المسج هنا ...',
      'send_message':'ابعت الرسالة',
      'Chat_Screen':'المحادثات',
      'type_your_message_here':'اكتب المسج هنا ...',
      'Create_Class':'انشأ حصة',
      'MyClasses_Screen':'حصصي',
      'Create_Class_Screen':'انشأ حصة',
      'Please fill the following_fields_to_Create_Class...':'يرجى ملء الحقول التالية لإنشاء الفصل...',
      'Enter_Your_Class_Name':'ادخل اسم الحصة',
      'Enter_Your_Class_Time':'ادخل وقت الحصة',
      'Enter_Your_Class_Date':'ادخل تاريخ الحصة',
      'Enter_Your_Name':'ادخل اسمك',
      'create':'موافقة',
      'Coaches_Screen':'المدربين',
      'Users_Screen':'المستخدمين',
      'Please Fill the_following_data_to add a Coach':'املأ الحقول التالية لأضافة مدرب...',
      'Enter_Coach_Name':'ادخل اسم المدرب',
      'Enter_Coach_Email':'ادخل البريد الاكتروني للمدرب',
      'Enter_Coach_Age':'ادخل عمر المدرب',
      'Enter_Coach_Major':'ادخل تخصص المدرب',
      'Enter_Coach_Password':'ادخل كلمة السر للمدرب',
      'Enter_Coach_Phone':'رقم المدرب',
      'Enter_Coach_Id':'الرقم الخاص بالمدرب',
      'Add_Coach':'اضافاة مدرب',
      'Please_Fill_the_following_fields':'املأ الحقول التالية',
      'Enter_Announcment_Title':'ادخل عنوان الملاحظة',
      'Enter_Announcment_Date':'ادخل تاريخ الملاحظة',
      'Enter_Announcment_Time':'ادخل وقت الملاحظة',
      'Enter_Announcment_News':'ادخل الخبر',
      'Add':'اضافة',
      'Messages':'المحادثات',
      'Announcement_Coach':'الملاحظات للمدرب',
      'Announcment_Screen':'الملاحظات للمستخدم',
      'About_App':'عن التطبيق',
      'Membership_renewal':'تجديد العضوية',
      'Please Chose The Way that You want_to_make_Renewal_using_it':'اختر الطريقة التي تريد تجديد العضوية من خلالها',







    },
    'en':{
      'Please Chose The Way that You want_to_make_Renewal_using_it':'Please Chose The Way that You want to make Renewal using it',
      'Membership_renewal':'Membership renewal',
      'About_App':'About_App',
      'Announcment_Screen':'Announcment Screen',
      'Announcement_Coach':'Announcement Coach',
      'Messages':'Messages',
      'Add':'Add',
      'Enter_Announcment_News':'Enter Announcment News',
      'Enter_Announcment_Time':'Enter Announcment Time',
      'Enter_Announcment_Date':'Enter Announcment Date',
      'Enter_Announcment_Title':'Enter Announcment Title',
      'Please_Fill_the_following_fields':'Please Fill the following fields',
      'Add_Coach':'Add Coach',
      'Enter_Coach_Id':'Enter Coach Id',
      'Enter_Coach_Phone':'Enter Coach Phone',
      'Enter_Coach_Password':'Enter Coach Password',
      'Enter_Coach_Major':'Enter Coach Major',
      'Enter_Coach_Age':'Enter Coach Age',
      'Enter_Coach_Email':'Enter Coach Email',
      'Enter_Coach_Name':'Enter Coach Name',
      'Please Fill the_following_data_to add a Coach':'Please Fill the following data to add a Coach ...',
      'Users_Screen':'Users Screen',
      'Coaches_Screen':'Coaches Screen',
      'create':'Create',
      'Enter_Your_Name':'Enter Your Name',
      'Enter_Your_Class_Date':'Enter Your Class Date',
      'Enter_Your_Class_Time':'Enter Your Class Time',
      'Enter_Your_Class_Name':'Enter Your Class Name',
      'Please fill the following_fields_to_Create_Class...':'Please fill the following fields to Create Class...',
      'Create_Class_Screen':'Create Class Screen',
      'MyClasses_Screen':'MyClasses Screen',
      'Create_Class':'Create Class',
      'type_your_message_here':'Type your message here...',
      'Chat_Screen':'Chat Screen',
      'send_message':'Send Message',
      'Write you_message_here':'Write you message here ...',
      'Get_in_touch_with_a_member_of_our_coaching_staff.':'Get in touch with a member of our coaching staff.',
      'Profile_Screen':'Profile Screen',
      'help':'Help',
      'about_app':'About App',
      'edit_profile':'Edit Profile',
      'language':'Language',
      'My_Classes':'My Classes',
      'decline':'Decline',
      'accept':'Accept',
      'Time_for_the_Class_:':'Time for the Class :',
      'coach_name_:':'Coach Name :',
      'class_title:':'Class Title:',
      'There_is _no_announcment':'There is no announcment',
      'announcements':'Announcements',
      'home':'Home',
      'classes':'Classes',
      'setting':'Setting',
  'logout':'Logout',
  'contact_us':'Contact Us',
      'account':'Account',
      'Menu':'Menu',
      'Setting_Screen':'Setting Screen',
      'Classes_Screen':'Classes Screen',
      'Home_Screen':'Home Screen',
      'sign_in':'Sign In',
      'sign_up':'Sign Up',
      'enter_your_email':'Enter your Email',
      'enter_your_password':'Enter Your Password',
      'dont_have_an_account':'Don\'t have an account ? ',
      'member_of_princess_nourah_university':'Member of Princess Nourah University',
      'No_I_am_not_a_member':'No, I am not a member',
      'Enter_your_Full_Name':'Enter your Full Name',
      'Enter_your_ID_Number':'Enter your ID Number',
      'Enter_your_Phone_Number':'Enter your Phone Number',
      'Enter_your_Age':'Enter your Age',
      'register':'Register',
      'Already_have_an_account_?':'Already have an account ?'

    }
  };

}